export const BTS_FACTS = [
  'RM was born Kim Namjoon in Ilsan and became known for translating during many early BTS overseas interviews.',
  'Jin studied acting at Konkuk University before debuting as a BTS vocalist.',
  'SUGA was active in Daegu underground music before joining Big Hit as a trainee.',
  'j-hope was part of a Gwangju street dance crew before BTS.',
  'Jimin trained in contemporary dance before becoming a BTS member.',
  'V was born Kim Taehyung in Daegu and grew up partly in Geochang.',
  'Jung Kook was born in Busan and joined Big Hit after auditioning for Superstar K.',
  'RM released his first solo mixtape in 2015 under the title RM.',
  'Jin co-wrote the solo song Awake, which appeared on the Wings album.',
  'SUGA has produced music under the name Agust D, an alias tied to Daegu Town and SUGA spelled backward.',
  'j-hope released the mixtape Hope World in 2018 before his later solo album Jack In The Box.',
  'Jimin was the final member added to the BTS lineup before debut.',
  'V acted in the Korean drama Hwarang: The Poet Warrior Youth.',
  'Jung Kook directed the music video for Life Goes On from the BE album.',
  'RM studied abroad briefly in New Zealand when he was young.',
  'Jin originally drew attention at Big Hit as a visual trainee before developing as a vocalist.',
  "SUGA helped write Tomorrow, one of BTS's early songs about youth anxiety.",
  "j-hope's birth name is Jung Hoseok, and his stage name points to his bright, hopeful role in the group.",
  'Jimin was born in Busan, the same city as Jung Kook.',
  "V's stage name was chosen to stand for victory.",
  "Jung Kook is often credited as BTS's main vocalist and has also contributed to production and video work.",
  'RM was the first BTS member recruited into what became the final group.',
  'Jin released the solo single The Astronaut with Coldplay contributing to the song.',
  "SUGA's solo documentary followed the making of his D-DAY album.",
  'j-hope was the first BTS member to headline a major U.S. music festival as a solo artist.',
  "Jimin's solo album FACE explored loneliness and self-reflection after the group's intense early-2020s years.",
  "V's solo album Layover leaned into jazz, soul, and relaxed R&B textures.",
  "Jung Kook's solo single Seven reached No. 1 on the Billboard Hot 100.",
  'RM has often cited reading and art museums as major influences on his lyrics and public projects.',
  "All seven BTS members renewed their contracts with BigHit Music before the group's planned full-team return.",
  'RM learned English in part by watching Friends with Korean subtitles.',
  "Jin's nickname Worldwide Handsome became a running joke he used in interviews.",
  'SUGA trained as a producer before debut and originally joined Big Hit with production as a major goal.',
  'j-hope won local dance competitions in Gwangju before becoming a trainee.',
  'Jimin attended Busan High School of Arts before transferring after joining Big Hit.',
  'V has used the photography name Vante, inspired by photographer Ante Badzim.',
  'Jung Kook painted and drew in several behind-the-scenes BTS projects.',
  'BTS debuted on June 13, 2013, with No More Dream.',
  'The BTS fandom name ARMY was announced in July 2013.',
  'The BTS Universe storyline began appearing across music videos and notes during The Most Beautiful Moment in Life era.',
  'BTS earned their first Korean music show win with I Need U in 2015.',
  'The Most Beautiful Moment in Life Pt. 1 included I Need U and Dope.',
  'The Wings album gave each BTS member a solo track in 2016.',
  'Love Yourself: Tear debuted at No. 1 on the Billboard 200 in 2018.',
  'Dynamite was BTS\'s first all-English single and was released in 2020.',
  'Butter was released in 2021 and became one of BTS\'s biggest English-language singles.',
  'Permission to Dance was co-written by Ed Sheeran.',
  'Life Goes On became known for its quiet, home-shot feeling during the BE era.',
  'Spring Day is often praised by fans for its long chart life in Korea.',
  'Mic Drop was remixed by Steve Aoki for an international release.',
  'Boy With Luv featured Halsey and appeared on Map of the Soul: Persona.',
  'BTS performed DNA at the American Music Awards in 2017.',
  'The group spoke at the United Nations in 2018 for the Generation Unlimited launch.',
  'Map of the Soul: 7 included solo and unit tracks alongside full-group songs.',
  'Black Swan was first introduced with an art-film performance by MN Dance Company.',
  'ON was released as the lead single from Map of the Soul: 7.',
  'BTS filmed the In the SOOP series in a countryside retreat setting.',
  'Run BTS began as a variety show where the members played games and challenges.',
  'Bon Voyage followed BTS members traveling together in different countries.',
  'RM\'s mono. playlist was released in 2018.',
  'RM\'s Indigo album included the song Wild Flower.',
  'Jin\'s Epiphany appeared on Love Yourself: Answer.',
  'Jin released the song Super Tuna as a playful trot-inspired track.',
  'SUGA\'s first Agust D mixtape was released in 2016.',
  'SUGA produced Suran\'s song Wine, which became a notable Korean chart hit.',
  'j-hope\'s Chicken Noodle Soup featured Becky G.',
  'j-hope released Jack In The Box with a darker, festival-ready solo sound.',
  'Jimin released Promise on SoundCloud in 2018.',
  'Jimin\'s Like Crazy reached No. 1 on the Billboard Hot 100 in 2023.',
  'V released Sweet Night for the Itaewon Class soundtrack.',
  'V\'s Layover album used relaxed R&B and jazz-influenced textures.',
  'Jung Kook\'s Euphoria became one of BTS\'s most recognized solo songs.',
  'Jung Kook performed Dreamers for the 2022 FIFA World Cup soundtrack.',
  'BTS\'s official light stick is called the ARMY Bomb.',
  'BTS often uses purple as a fan color after V popularized the phrase I purple you.',
  'The Love Yourself campaign with UNICEF began in 2017.',
  'BTS donated and encouraged support for the Black Lives Matter movement in 2020.',
  'BTS\'s TinyTAN characters are stylized animated versions of the members.',
  'BT21 characters were created with LINE FRIENDS and each member helped design one.',
  'BTS recorded many early dance practices in the Big Hit practice room.',
  'The group name Bangtan Sonyeondan translates roughly as Bulletproof Boy Scouts.',
  'Beyond the Scene became an added English meaning for BTS in 2017.',
  'BTS released their Japanese studio album Wake Up in 2014.',
  'Blood Sweat & Tears was the lead single from Wings.',
  'Save Me used a one-take style music video filmed outdoors.',
  'Not Today was released during the You Never Walk Alone era.',
  'The Truth Untold is a vocal-line song featuring production by Steve Aoki.',
  'Ddaeng was released by the rap line for BTS Festa in 2018.',
  'BTS Festa is the group\'s yearly anniversary celebration with special content for fans.',
  'The song 2! 3! is often treated as an early fan-dedicated comfort song.',
] as const;
