export const BTS_FACTS = [
  'RM was born Kim Namjoon in Ilsan and became known for translating during many early BTS overseas interviews.',
  'Jin studied acting at Konkuk University before debuting as a BTS vocalist.',
  'SUGA was active in Daegu underground music before joining Big Hit as a trainee.',
  'j-hope was part of a Gwangju street dance crew before BTS.',
  'Jimin trained in contemporary dance before becoming a BTS member.',
  'V was born Kim Taehyung in Daegu and grew up partly in Geochang.',
  'Jung Kook was born in Busan and joined Big Hit after auditioning for Superstar K.',
  'RM released his first solo mixtape in 2015 under the title RM.',
  'Jin co-wrote the solo song Awake, which appeared on the Wings album.',
  'SUGA has produced music under the name Agust D, an alias tied to Daegu Town and SUGA spelled backward.',
  'j-hope released the mixtape Hope World in 2018 before his later solo album Jack In The Box.',
  'Jimin was the final member added to the BTS lineup before debut.',
  'V acted in the Korean drama Hwarang: The Poet Warrior Youth.',
  'Jung Kook directed the music video for Life Goes On from the BE album.',
  'RM studied abroad briefly in New Zealand when he was young.',
  'Jin originally drew attention at Big Hit as a visual trainee before developing as a vocalist.',
  "SUGA helped write Tomorrow, one of BTS's early songs about youth anxiety.",
  "j-hope's birth name is Jung Hoseok, and his stage name points to his bright, hopeful role in the group.",
  'Jimin was born in Busan, the same city as Jung Kook.',
  "V's stage name was chosen to stand for victory.",
  "Jung Kook is often credited as BTS's main vocalist and has also contributed to production and video work.",
  'RM was the first BTS member recruited into what became the final group.',
  'Jin released the solo single The Astronaut with Coldplay contributing to the song.',
  "SUGA's solo documentary followed the making of his D-DAY album.",
  'j-hope was the first BTS member to headline a major U.S. music festival as a solo artist.',
  "Jimin's solo album FACE explored loneliness and self-reflection after the group's intense early-2020s years.",
  "V's solo album Layover leaned into jazz, soul, and relaxed R&B textures.",
  "Jung Kook's solo single Seven reached No. 1 on the Billboard Hot 100.",
  'RM has often cited reading and art museums as major influences on his lyrics and public projects.',
  "All seven BTS members renewed their contracts with BigHit Music before the group's planned full-team return.",
  'RM learned English in part by watching Friends with Korean subtitles.',
  "Jin's nickname Worldwide Handsome became a running joke he used in interviews.",
  'SUGA trained as a producer before debut and originally joined Big Hit with production as a major goal.',
  'j-hope won local dance competitions in Gwangju before becoming a trainee.',
  'Jimin attended Busan High School of Arts before transferring after joining Big Hit.',
  'V has used the photography name Vante, inspired by photographer Ante Badzim.',
  'Jung Kook painted and drew in several behind-the-scenes BTS projects.',
  'BTS debuted on June 13, 2013, with No More Dream.',
  'The BTS fandom name ARMY was announced in July 2013.',
  'The BTS Universe storyline began appearing across music videos and notes during The Most Beautiful Moment in Life era.',
] as const;
